/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL.impl;

import fr.imt.ales.springdsl.springDSL.AbstractKeyValue;
import fr.imt.ales.springdsl.springDSL.SpringDSLPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Key Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractKeyValueImpl extends MinimalEObjectImpl.Container implements AbstractKeyValue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractKeyValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringDSLPackage.Literals.ABSTRACT_KEY_VALUE;
  }

} //AbstractKeyValueImpl
