/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL.impl;

import fr.imt.ales.springdsl.springDSL.BeforeAdvise;
import fr.imt.ales.springdsl.springDSL.SpringDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Before Advise</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BeforeAdviseImpl extends AdviseImpl implements BeforeAdvise
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BeforeAdviseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringDSLPackage.Literals.BEFORE_ADVISE;
  }

} //BeforeAdviseImpl
