/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL.impl;

import fr.imt.ales.springdsl.springDSL.PropertyOverride;
import fr.imt.ales.springdsl.springDSL.SpringDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property Override</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PropertyOverrideImpl extends PropertyHolderImpl implements PropertyOverride
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyOverrideImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringDSLPackage.Literals.PROPERTY_OVERRIDE;
  }

} //PropertyOverrideImpl
