/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.spring.ui.AbstractSpringConfigDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SpringConfigDslUiModule extends AbstractSpringConfigDslUiModule {
  public SpringConfigDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
