/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.spring.springConfigDsl.AopAspect;
import org.xtext.spring.springConfigDsl.SpringConfigDslFactory;
import org.xtext.spring.springConfigDsl.SpringConfigDslPackage;

/**
 * This is the item provider adapter for a {@link org.xtext.spring.springConfigDsl.AopAspect} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AopAspectItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AopAspectItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addNamePropertyDescriptor(object);
			addOrderPropertyDescriptor(object);
			addBackingBeanRefPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Name feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addNamePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_AopAspect_name_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_AopAspect_name_feature", "_UI_AopAspect_type"),
				 SpringConfigDslPackage.Literals.AOP_ASPECT__NAME,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Order feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addOrderPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_AopAspect_order_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_AopAspect_order_feature", "_UI_AopAspect_type"),
				 SpringConfigDslPackage.Literals.AOP_ASPECT__ORDER,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Backing Bean Ref feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addBackingBeanRefPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_AopAspect_backingBeanRef_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_AopAspect_backingBeanRef_feature", "_UI_AopAspect_type"),
				 SpringConfigDslPackage.Literals.AOP_ASPECT__BACKING_BEAN_REF,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(SpringConfigDslPackage.Literals.AOP_ASPECT__AOP_POINTCUTS);
			childrenFeatures.add(SpringConfigDslPackage.Literals.AOP_ASPECT__DECLARED_PARENTS);
			childrenFeatures.add(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns AopAspect.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/AopAspect"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((AopAspect)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_AopAspect_type") :
			getString("_UI_AopAspect_type") + " " + label;
	}
	

	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(AopAspect.class)) {
			case SpringConfigDslPackage.AOP_ASPECT__NAME:
			case SpringConfigDslPackage.AOP_ASPECT__ORDER:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case SpringConfigDslPackage.AOP_ASPECT__AOP_POINTCUTS:
			case SpringConfigDslPackage.AOP_ASPECT__DECLARED_PARENTS:
			case SpringConfigDslPackage.AOP_ASPECT__ADVISES:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__AOP_POINTCUTS,
				 SpringConfigDslFactory.eINSTANCE.createAopPointcut()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__DECLARED_PARENTS,
				 SpringConfigDslFactory.eINSTANCE.createDeclareParents()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createAdvise()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createBeforeAdvise()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createAfterAdvise()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createAroundAdvise()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createAfterReturning()));

		newChildDescriptors.add
			(createChildParameter
				(SpringConfigDslPackage.Literals.AOP_ASPECT__ADVISES,
				 SpringConfigDslFactory.eINSTANCE.createAfterThowing()));
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return SpringConfigDslEditPlugin.INSTANCE;
	}

}
