/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.spring.springConfigDsl.AopInclude;
import org.xtext.spring.springConfigDsl.Component;
import org.xtext.spring.springConfigDsl.SpringConfigDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Aop Include</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.springConfigDsl.impl.AopIncludeImpl#getAopInclude <em>Aop Include</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AopIncludeImpl extends MinimalEObjectImpl.Container implements AopInclude
{
  /**
   * The cached value of the '{@link #getAopInclude() <em>Aop Include</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAopInclude()
   * @generated
   * @ordered
   */
  protected Component aopInclude;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AopIncludeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringConfigDslPackage.Literals.AOP_INCLUDE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Component getAopInclude()
  {
    if (aopInclude != null && aopInclude.eIsProxy())
    {
      InternalEObject oldAopInclude = (InternalEObject)aopInclude;
      aopInclude = (Component)eResolveProxy(oldAopInclude);
      if (aopInclude != oldAopInclude)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE, oldAopInclude, aopInclude));
      }
    }
    return aopInclude;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Component basicGetAopInclude()
  {
    return aopInclude;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAopInclude(Component newAopInclude)
  {
    Component oldAopInclude = aopInclude;
    aopInclude = newAopInclude;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE, oldAopInclude, aopInclude));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE:
        if (resolve) return getAopInclude();
        return basicGetAopInclude();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE:
        setAopInclude((Component)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE:
        setAopInclude((Component)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SpringConfigDslPackage.AOP_INCLUDE__AOP_INCLUDE:
        return aopInclude != null;
    }
    return super.eIsSet(featureID);
  }

} //AopIncludeImpl
