/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.spring.springConfigDsl.SpringConfigDslPackage;
import org.xtext.spring.springConfigDsl.SpringSecurity;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Spring Security</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SpringSecurityImpl extends MinimalEObjectImpl.Container implements SpringSecurity
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpringSecurityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringConfigDslPackage.Literals.SPRING_SECURITY;
  }

} //SpringSecurityImpl
