/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation Config</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAnnotationConfig()
 * @model
 * @generated
 */
public interface AnnotationConfig extends Context
{
} // AnnotationConfig
