/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aop Aspect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getName <em>Name</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getOrder <em>Order</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getBackingBeanRef <em>Backing Bean Ref</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getAopPointcuts <em>Aop Pointcuts</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getDeclaredParents <em>Declared Parents</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.AopAspect#getAdvises <em>Advises</em>}</li>
 * </ul>
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect()
 * @model
 * @generated
 */
public interface AopAspect extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.AopAspect#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see #setOrder(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_Order()
   * @model
   * @generated
   */
  String getOrder();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.AopAspect#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see #getOrder()
   * @generated
   */
  void setOrder(String value);

  /**
   * Returns the value of the '<em><b>Backing Bean Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Backing Bean Ref</em>' reference.
   * @see #setBackingBeanRef(Component)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_BackingBeanRef()
   * @model
   * @generated
   */
  Component getBackingBeanRef();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.AopAspect#getBackingBeanRef <em>Backing Bean Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Backing Bean Ref</em>' reference.
   * @see #getBackingBeanRef()
   * @generated
   */
  void setBackingBeanRef(Component value);

  /**
   * Returns the value of the '<em><b>Aop Pointcuts</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.ales.springdsl.springDSL.AopPointcut}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aop Pointcuts</em>' containment reference list.
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_AopPointcuts()
   * @model containment="true"
   * @generated
   */
  EList<AopPointcut> getAopPointcuts();

  /**
   * Returns the value of the '<em><b>Declared Parents</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.ales.springdsl.springDSL.DeclareParents}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declared Parents</em>' containment reference list.
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_DeclaredParents()
   * @model containment="true"
   * @generated
   */
  EList<DeclareParents> getDeclaredParents();

  /**
   * Returns the value of the '<em><b>Advises</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.ales.springdsl.springDSL.Advise}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Advises</em>' containment reference list.
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAopAspect_Advises()
   * @model containment="true"
   * @generated
   */
  EList<Advise> getAdvises();

} // AopAspect
