/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Auto Wired Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getAutoWiredType()
 * @model
 * @generated
 */
public enum AutoWiredType implements Enumerator
{
  /**
   * The '<em><b>DEFAULT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEFAULT_VALUE
   * @generated
   * @ordered
   */
  DEFAULT(0, "DEFAULT", "\"default\""),

  /**
   * The '<em><b>NO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NO_VALUE
   * @generated
   * @ordered
   */
  NO(1, "NO", "\"no\""),

  /**
   * The '<em><b>BYNAME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BYNAME_VALUE
   * @generated
   * @ordered
   */
  BYNAME(2, "BYNAME", "\"byName\""),

  /**
   * The '<em><b>BYTYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BYTYPE_VALUE
   * @generated
   * @ordered
   */
  BYTYPE(3, "BYTYPE", "\"byType\""),

  /**
   * The '<em><b>CONSTRUCTOR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONSTRUCTOR_VALUE
   * @generated
   * @ordered
   */
  CONSTRUCTOR(4, "CONSTRUCTOR", "\"constructor\"");

  /**
   * The '<em><b>DEFAULT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEFAULT
   * @model literal="\"default\""
   * @generated
   * @ordered
   */
  public static final int DEFAULT_VALUE = 0;

  /**
   * The '<em><b>NO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NO
   * @model literal="\"no\""
   * @generated
   * @ordered
   */
  public static final int NO_VALUE = 1;

  /**
   * The '<em><b>BYNAME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BYNAME
   * @model literal="\"byName\""
   * @generated
   * @ordered
   */
  public static final int BYNAME_VALUE = 2;

  /**
   * The '<em><b>BYTYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BYTYPE
   * @model literal="\"byType\""
   * @generated
   * @ordered
   */
  public static final int BYTYPE_VALUE = 3;

  /**
   * The '<em><b>CONSTRUCTOR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONSTRUCTOR
   * @model literal="\"constructor\""
   * @generated
   * @ordered
   */
  public static final int CONSTRUCTOR_VALUE = 4;

  /**
   * An array of all the '<em><b>Auto Wired Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final AutoWiredType[] VALUES_ARRAY =
    new AutoWiredType[]
    {
      DEFAULT,
      NO,
      BYNAME,
      BYTYPE,
      CONSTRUCTOR,
    };

  /**
   * A public read-only list of all the '<em><b>Auto Wired Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<AutoWiredType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Auto Wired Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AutoWiredType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AutoWiredType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Auto Wired Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AutoWiredType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      AutoWiredType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Auto Wired Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static AutoWiredType get(int value)
  {
    switch (value)
    {
      case DEFAULT_VALUE: return DEFAULT;
      case NO_VALUE: return NO;
      case BYNAME_VALUE: return BYNAME;
      case BYTYPE_VALUE: return BYTYPE;
      case CONSTRUCTOR_VALUE: return CONSTRUCTOR;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private AutoWiredType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //AutoWiredType
