/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Factory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.Factory#getFactoryBean <em>Factory Bean</em>}</li>
 * </ul>
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getFactory()
 * @model
 * @generated
 */
public interface Factory extends ClassOrFactory
{
  /**
   * Returns the value of the '<em><b>Factory Bean</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Factory Bean</em>' reference.
   * @see #setFactoryBean(Component)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getFactory_FactoryBean()
   * @model
   * @generated
   */
  Component getFactoryBean();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.Factory#getFactoryBean <em>Factory Bean</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Factory Bean</em>' reference.
   * @see #getFactoryBean()
   * @generated
   */
  void setFactoryBean(Component value);

} // Factory
