/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MVC</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getMVC()
 * @model
 * @generated
 */
public interface MVC extends EObject
{
} // MVC
