/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Props</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.Props#getProps <em>Props</em>}</li>
 * </ul>
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getProps()
 * @model
 * @generated
 */
public interface Props extends Collection
{
  /**
   * Returns the value of the '<em><b>Props</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.ales.springdsl.springDSL.Prop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Props</em>' containment reference list.
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getProps_Props()
   * @model containment="true"
   * @generated
   */
  EList<Prop> getProps();

} // Props
