/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Placeholder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.PropertyPlaceholder#getSystemPropertiesMode <em>System Properties Mode</em>}</li>
 * </ul>
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getPropertyPlaceholder()
 * @model
 * @generated
 */
public interface PropertyPlaceholder extends PropertyHolder
{
  /**
   * Returns the value of the '<em><b>System Properties Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>System Properties Mode</em>' attribute.
   * @see #setSystemPropertiesMode(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getPropertyPlaceholder_SystemPropertiesMode()
   * @model
   * @generated
   */
  String getSystemPropertiesMode();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.PropertyPlaceholder#getSystemPropertiesMode <em>System Properties Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System Properties Mode</em>' attribute.
   * @see #getSystemPropertiesMode()
   * @generated
   */
  void setSystemPropertiesMode(String value);

} // PropertyPlaceholder
