/**
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.springDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Util List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.UtilList#getName <em>Name</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.UtilList#getListClass <em>List Class</em>}</li>
 *   <li>{@link fr.imt.ales.springdsl.springDSL.UtilList#getScope <em>Scope</em>}</li>
 * </ul>
 *
 * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getUtilList()
 * @model
 * @generated
 */
public interface UtilList extends sList
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getUtilList_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.UtilList#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>List Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Class</em>' attribute.
   * @see #setListClass(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getUtilList_ListClass()
   * @model
   * @generated
   */
  String getListClass();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.UtilList#getListClass <em>List Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Class</em>' attribute.
   * @see #getListClass()
   * @generated
   */
  void setListClass(String value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' attribute.
   * @see #setScope(String)
   * @see fr.imt.ales.springdsl.springDSL.SpringDSLPackage#getUtilList_Scope()
   * @model
   * @generated
   */
  String getScope();

  /**
   * Sets the value of the '{@link fr.imt.ales.springdsl.springDSL.UtilList#getScope <em>Scope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' attribute.
   * @see #getScope()
   * @generated
   */
  void setScope(String value);

} // UtilList
