/*
 * generated by Xtext 2.14.0
 */
package org.xtext.spring.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.spring.parser.antlr.internal.InternalSpringConfigDslParser;
import org.xtext.spring.services.SpringConfigDslGrammarAccess;

public class SpringConfigDslParser extends AbstractAntlrParser {

	@Inject
	private SpringConfigDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT");
	}
	

	@Override
	protected InternalSpringConfigDslParser createParser(XtextTokenStream stream) {
		return new InternalSpringConfigDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SpringProject";
	}

	public SpringConfigDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpringConfigDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
