/*
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.ui.tests;

import com.google.inject.Injector;
import fr.imt.ales.springdsl.ui.internal.SpringdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SpringDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpringdslActivator.getInstance().getInjector("fr.imt.ales.springdsl.SpringDSL");
	}

}
