/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>After Advise</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getAfterAdvise()
 * @model
 * @generated
 */
public interface AfterAdvise extends Advise
{
} // AfterAdvise
