/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aop Aspect JAutoproxy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.springConfigDsl.AopAspectJAutoproxy#getAopincludes <em>Aopincludes</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getAopAspectJAutoproxy()
 * @model
 * @generated
 */
public interface AopAspectJAutoproxy extends Aspect
{
  /**
	 * Returns the value of the '<em><b>Aopincludes</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.spring.springConfigDsl.AopInclude}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aopincludes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Aopincludes</em>' containment reference list.
	 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getAopAspectJAutoproxy_Aopincludes()
	 * @model containment="true"
	 * @generated
	 */
  EList<AopInclude> getAopincludes();

} // AopAspectJAutoproxy
