/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aop Scoped Proxy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.springConfigDsl.AopScopedProxy#getProxyTargetClass <em>Proxy Target Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getAopScopedProxy()
 * @model
 * @generated
 */
public interface AopScopedProxy extends EObject
{
  /**
	 * Returns the value of the '<em><b>Proxy Target Class</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proxy Target Class</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Proxy Target Class</em>' attribute.
	 * @see #setProxyTargetClass(String)
	 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getAopScopedProxy_ProxyTargetClass()
	 * @model
	 * @generated
	 */
  String getProxyTargetClass();

  /**
	 * Sets the value of the '{@link org.xtext.spring.springConfigDsl.AopScopedProxy#getProxyTargetClass <em>Proxy Target Class</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Proxy Target Class</em>' attribute.
	 * @see #getProxyTargetClass()
	 * @generated
	 */
  void setProxyTargetClass(String value);

} // AopScopedProxy
