/**
 * generated by Xtext 2.17.0.M3
 */
package org.xtext.spring.springConfigDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.springConfigDsl.Collection#getValueType <em>Value Type</em>}</li>
 *   <li>{@link org.xtext.spring.springConfigDsl.Collection#getMerge <em>Merge</em>}</li>
 *   <li>{@link org.xtext.spring.springConfigDsl.Collection#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getCollection()
 * @model
 * @generated
 */
public interface Collection extends AbstractArtefact
{
  /**
   * Returns the value of the '<em><b>Value Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Type</em>' attribute.
   * @see #setValueType(String)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getCollection_ValueType()
   * @model
   * @generated
   */
  String getValueType();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.Collection#getValueType <em>Value Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Type</em>' attribute.
   * @see #getValueType()
   * @generated
   */
  void setValueType(String value);

  /**
   * Returns the value of the '<em><b>Merge</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.spring.springConfigDsl.DefaultableBoolean}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Merge</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Merge</em>' attribute.
   * @see org.xtext.spring.springConfigDsl.DefaultableBoolean
   * @see #setMerge(DefaultableBoolean)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getCollection_Merge()
   * @model
   * @generated
   */
  DefaultableBoolean getMerge();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.Collection#getMerge <em>Merge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Merge</em>' attribute.
   * @see org.xtext.spring.springConfigDsl.DefaultableBoolean
   * @see #getMerge()
   * @generated
   */
  void setMerge(DefaultableBoolean value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getCollection_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.Collection#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // Collection
