/**
 * generated by Xtext 2.12.0
 */
package org.xtext.spring.springConfigDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MVC</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getMVC()
 * @model
 * @generated
 */
public interface MVC extends EObject
{
} // MVC
