/**
 * generated by Xtext 2.17.0
 */
package org.xtext.spring.springConfigDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Util Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.springConfigDsl.UtilSet#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.spring.springConfigDsl.UtilSet#getSetClass <em>Set Class</em>}</li>
 *   <li>{@link org.xtext.spring.springConfigDsl.UtilSet#getScope <em>Scope</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getUtilSet()
 * @model
 * @generated
 */
public interface UtilSet extends sSet
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getUtilSet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.UtilSet#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Set Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set Class</em>' attribute.
   * @see #setSetClass(String)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getUtilSet_SetClass()
   * @model
   * @generated
   */
  String getSetClass();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.UtilSet#getSetClass <em>Set Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set Class</em>' attribute.
   * @see #getSetClass()
   * @generated
   */
  void setSetClass(String value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' attribute.
   * @see #setScope(String)
   * @see org.xtext.spring.springConfigDsl.SpringConfigDslPackage#getUtilSet_Scope()
   * @model
   * @generated
   */
  String getScope();

  /**
   * Sets the value of the '{@link org.xtext.spring.springConfigDsl.UtilSet#getScope <em>Scope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' attribute.
   * @see #getScope()
   * @generated
   */
  void setScope(String value);

} // UtilSet
