/*
 * generated by Xtext 2.18.0
 */
package fr.imt.ales.springdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpringDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/imt/ales/springdsl/parser/antlr/internal/InternalSpringDSL.tokens");
	}
}
